### ISSUE TITLE
env[:HOME] can't modify frozen Hash

### ISSUE THREAD

**Issue by headcrabmeat** [brholtkamp/msys2-cookbook#4]
Hi looks I'm getting `can't modify frozen object` issue( see https://github.com/chef/chef/issues/3734 for details)

Here is the client error output:
```
    * msys2_execute[update MSYS2] action run[2017-05-23T10:58:50+03:00] INFO: Processing msys2_execute[update MSYS2] act
ion run (.../cookbooks/msys2/resources/update.rb line 10)


      ================================================================================
      Error executing action `run` on resource 'msys2_execute[update MSYS2]'
      ================================================================================

      RuntimeError
      ------------
      can't modify frozen Hash

      Cookbook Trace:
      ---------------
     .../cache/cookbooks/msys2/libraries/msys2_command_helper.rb:28:in `generate_env'
      .../cache/cookbooks/msys2/resources/execute.rb:22:in `block in class_from_file'

      Resource Declaration:
      ---------------------
      # In .../cookbooks/msys2/resources/update.rb

       10:   msys2_execute 'update MSYS2' do
       11:     command ['pacman', '--sync', '--sysupgrade', '--refresh', '--noconfirm', '--noprogressbar']
       12:   end
       13: end

      Compiled Resource:
      ------------------
      # Declared in .../cookbooks/msys2/resources/update.rb:10:in `block in class_from_file'

      msys2_execute("update MSYS2") do
        action [:run]
        default_guard_interpreter :default
        declared_type :msys2_execute
        cookbook_name "msys2"
        command ["pacman", "--sync", "--sysupgrade", "--refresh", "--noconfirm", "--noprogressbar"]
      end

      System Info:
      ------------
      chef_version=13.0.118
      platform=windows
      platform_version=10.0.14393
      ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
```

**Comment by brholtkamp** [comment]
Interesting, this happened on your initial run of the cookbook?  I've got a machine provisioned and it hasn't bumped into this hiccup yet but it was bootstrapped a while ago.

PR looks good, gonna go ahead and push it through.

**Comment by headcrabmeat** [comment]
Yep, just saw it on a new bootstrapped host.
